version: '3'
services: 
  app-frontend:
    container_name: frontend
    image: nubimari/app-frontend
    build: ./service1
    deploy:
      replicas: 2
    ports:
    - "5000:5000"
  
  app-names:
    container_name: names
    image: nubimari/app-names
    build: ./service2
    deploy:
     replicas: 2
    ports:
    - "5001:5001"
  
  app-fruits:
    container_name: fruits
    image: nubimari/app-fruits
    build: ./service3
    deploy:
      replicas: 2
    ports: 
    - "5002:5002"
  
  app-prizes:
    container_name: prizes
    image: nubimari/app-prizes
    build: ./service4
    deploy:
      replicas: 2
    ports:
    - "5003:5003"
