version: '3.8'
services: 
  app-frontend:
    image: nubimari/app-frontend
    build: ./service1
    deploy:
      replicas: 2
    ports:
    - "5000:5000"
  
  app-names:
    image: nubimari/app-names
    build: ./service2
    deploy:
     replicas: 2
    ports:
    - "5001:5001"
  
  app-fruits:
    image: nubimari/app-fruits
    build: ./service3
    deploy:
      replicas: 2
    ports: 
    - "5002:5002"
  
  app-prizes:
    image: nubimari/app-prizes
    build: ./service4
    deploy:
      replicas: 2
    ports:
    - "5003:5003"

  nginx-server:
    image: nginx:alpine
    container_name: nginx
    deploy:
      replicas: 2
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
