version: '3.7'
services:
  app-frontend:
    image: app-frontend:latest
    ports:
    - 5000:5000
  app-names:
    image: app-names:latest
    ports:
    - 5001:5001
  app-fruits:
    image: app-fruits:latest
    ports:
    - 5002:5002
  app-prizes:
    image: app-prizes:latest
    ports:
    - 5003:5003
