version: '3.7'
services:
  mysql:
    image: 
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
  flask-app: 
    build: nginx:latest
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
  nginx: 
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx.conf
