---
- name: install docker
  become: true
  hosts: my-hosts
  roles:
    - docker

- name: install docker
  become: true
  hosts: worker
  roles:
    - docker

- name: initialise docker swarm
  become: true
  hosts: manager
  roles:
    - manager

- name: add workers to swarm
  become: true
  hosts: worker
  roles:
    - worker
